version: '3'

services:
  bolt-diy-auth:
    build: .
    ports:
      - "8080:80"
      - "3000:3000"  # Also exposing bolt.diy application port
    environment:
      - AUTH_USER=admin
      - AUTH_PASSWORD=railway
      # Add any specific bolt.diy environment variables here
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf.template
      - ./start.sh:/start.sh
    restart: unless-stopped